spring.application.name=gotomock
server.port=8081

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/gotomock
spring.datasource.username=root
spring.datasource.password=Prax@1234

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect